데이터 EDA  
=====
단지코드의 경우 동일 단지코드의 전용면적별 세대수의 합이 각 열의 총세대수와 일치 또한 공가수가 각 전용면적의 공가수가 아닌 단지의 공가 수로 보이므로 전용면적이 다른 경우가 있어서 각 열의 공가수가 적절한 데이터인지 의문이 듬.

기본데이터 탐색시 노선 수 및 버스 정류장 수의 데이터에 누락 존재 이 값을 어떻게 채울 것인가?

1. 임대건물구분이 상가인 겯우  
 1-1) 상가인 경우 임대보증금 및 임대료가 기입되지 않음 ->이를 어떻게 해결할 것인가?  
 1-2) 상가인 경우 공급유형이 임대상가로 전부 일치  
 1-3) 상가인 경우 자격유형이 D만 존재  

2. 임대건물구분이 아파트인 경우
 2-1) 지역 건물들이 상가보다는 다양하게 분포 (상가의 경우 : 강원도 충청남도 경상남도 대전광역시 부산광역시 제주특별자치도만 존재)  
 2-2) 공급 유형이 상가대비 많으며 일부 레이블의 경우 기간 차이만 존재 (예: 공공임대 5년 10년 50년 분납)
 2-3) 자격유형이 A부터 O까지 존재
 2-4) 암대보증금과 임대료에 '-'로 데이터가 들어있는 데이터가 존재 또한 NaN 값도 존재
 확인결과 총 3개의 단지에서 데이터가 '-'로 입력되어 있음. C1326, C1786, C2186

In [1]:
import numpy as np 
import pandas as pd

In [2]:
train = pd.read_csv('train.csv') #2952 X 15 423개의 단지가 존재
test = pd.read_csv('test.csv') #1022 X 14

In [3]:
train

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수,등록차량수
0,C2483,900,아파트,경상북도,국민임대,39.72,134,38.0,A,15667000,103680,0.0,3.0,1425.0,1015.0
1,C2483,900,아파트,경상북도,국민임대,39.72,15,38.0,A,15667000,103680,0.0,3.0,1425.0,1015.0
2,C2483,900,아파트,경상북도,국민임대,51.93,385,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
3,C2483,900,아파트,경상북도,국민임대,51.93,15,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
4,C2483,900,아파트,경상북도,국민임대,51.93,41,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947,C2532,239,아파트,강원도,국민임대,49.20,19,7.0,A,11346000,116090,0.0,1.0,166.0,146.0
2948,C2532,239,아파트,강원도,국민임대,51.08,34,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2949,C2532,239,아파트,강원도,국민임대,51.73,34,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2950,C2532,239,아파트,강원도,국민임대,51.96,114,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2951,C2532,239,아파트,강원도,국민임대,54.95,19,7.0,A,14830000,151030,0.0,1.0,166.0,146.0

In [4]:
train['공급유형'].unique()

array(['국민임대', '공공임대(50년)', '영구임대', '임대상가', '공공임대(10년)', '공공임대(분납)',
       '장기전세', '공공분양', '행복주택', '공공임대(5년)'], dtype=object)

In [5]:
train['임대건물구분'].unique()

array(['아파트', '상가'], dtype=object)

In [6]:
ex = train.loc[train.임대건물구분 == '상가']

In [7]:
ex['공급유형'].unique()

array(['임대상가'], dtype=object)

In [8]:
ex['임대료'].unique()

array([nan], dtype=object)

In [19]:
ex.자격유형.unique()

array(['D'], dtype=object)

In [21]:
ex.지역.unique()

array(['강원도', '충청남도', '경상남도', '대전광역시', '부산광역시', '제주특별자치도'], dtype=object)

In [9]:
ex

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수,등록차량수
88,C1925,601,상가,강원도,임대상가,32.10,1,9.0,D,NaN,NaN,0.0,4.0,117.0,75.0
89,C1925,601,상가,강원도,임대상가,32.10,1,9.0,D,NaN,NaN,0.0,4.0,117.0,75.0
90,C1925,601,상가,강원도,임대상가,32.10,1,9.0,D,NaN,NaN,0.0,4.0,117.0,75.0
91,C1925,601,상가,강원도,임대상가,72.16,1,9.0,D,NaN,NaN,0.0,4.0,117.0,75.0
101,C1874,619,상가,충청남도,임대상가,12.62,1,2.0,D,NaN,NaN,NaN,2.0,97.0,62.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,C2571,481,상가,경상남도,임대상가,31.84,1,5.0,D,NaN,NaN,0.0,1.0,65.0,62.0
835,C2571,481,상가,경상남도,임대상가,31.84,1,5.0,D,NaN,NaN,0.0,1.0,65.0,62.0
836,C2571,481,상가,경상남도,임대상가,31.84,1,5.0,D,NaN,NaN,0.0,1.0,65.0,62.0
837,C2571,481,상가,경상남도,임대상가,31.84,1,5.0,D,NaN,NaN,0.0,1.0,65.0,62.0
838,C2571,481,상가,경상남도,임대상가,126.65,1,5.0,D,NaN,NaN,0.0,1.0,65.0,62.0

In [13]:
np.shape(train['단지코드'].unique())

(423,)

In [14]:
ex2 = train.loc[train.임대건물구분 == '아파트']

In [17]:
ex2

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수,등록차량수
0,C2483,900,아파트,경상북도,국민임대,39.72,134,38.0,A,15667000,103680,0.0,3.0,1425.0,1015.0
1,C2483,900,아파트,경상북도,국민임대,39.72,15,38.0,A,15667000,103680,0.0,3.0,1425.0,1015.0
2,C2483,900,아파트,경상북도,국민임대,51.93,385,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
3,C2483,900,아파트,경상북도,국민임대,51.93,15,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
4,C2483,900,아파트,경상북도,국민임대,51.93,41,38.0,A,27304000,184330,0.0,3.0,1425.0,1015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947,C2532,239,아파트,강원도,국민임대,49.20,19,7.0,A,11346000,116090,0.0,1.0,166.0,146.0
2948,C2532,239,아파트,강원도,국민임대,51.08,34,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2949,C2532,239,아파트,강원도,국민임대,51.73,34,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2950,C2532,239,아파트,강원도,국민임대,51.96,114,7.0,A,14005000,142310,0.0,1.0,166.0,146.0
2951,C2532,239,아파트,강원도,국민임대,54.95,19,7.0,A,14830000,151030,0.0,1.0,166.0,146.0

In [18]:
ex2.자격유형.unique()

array(['A', 'B', 'C', 'E', 'F', 'G', 'H', 'I', 'D', 'J', 'K', 'L', 'M',
       'N', 'O'], dtype=object)

In [22]:
ex2.지역.unique()

array(['경상북도', '경상남도', '대전광역시', '경기도', '전라북도', '강원도', '광주광역시', '충청남도',
       '부산광역시', '제주특별자치도', '울산광역시', '충청북도', '전라남도', '대구광역시', '서울특별시',
       '세종특별자치시'], dtype=object)

In [30]:
np.shape(ex2['임대료'].unique())

(996,)

In [29]:
ex2.loc[ex2.임대보증금 == '-']

,단지코드,총세대수,임대건물구분,지역,공급유형,전용면적,전용면적별세대수,공가수,자격유형,임대보증금,임대료,도보 10분거리 내 지하철역 수(환승노선 수 반영),도보 10분거리 내 버스정류장 수,단지내주차면수,등록차량수
2547,C1326,1934,아파트,부산광역시,국민임대,24.72,472,43.0,H,-,-,0.0,4.0,1670.0,1153.0
2548,C1326,1934,아파트,부산광역시,국민임대,24.79,104,43.0,H,-,-,0.0,4.0,1670.0,1153.0
2549,C1326,1934,아파트,부산광역시,국민임대,26.83,590,43.0,H,-,-,0.0,4.0,1670.0,1153.0
2550,C1326,1934,아파트,부산광역시,국민임대,37.70,464,43.0,H,-,-,0.0,4.0,1670.0,1153.0
2551,C1326,1934,아파트,부산광역시,국민임대,46.94,304,43.0,H,-,-,0.0,4.0,1670.0,1153.0
2680,C1786,480,아파트,강원도,행복주택,16.91,156,25.0,K,-,-,0.0,3.0,338.0,345.0
2681,C1786,480,아파트,강원도,행복주택,26.90,136,25.0,K,-,-,0.0,3.0,338.0,345.0
2682,C1786,480,아파트,강원도,행복주택,26.90,72,25.0,K,-,-,0.0,3.0,338.0,345.0
2683,C1786,480,아파트,강원도,행복주택,26.90,24,25.0,K,-,-,0.0,3.0,338.0,345.0
2906,C2186,924,아파트,대구광역시,국민임대,29.17,238,0.0,H,-,-,0.0,8.0,664.0,744.0
2907,C2186,924,아파트,대구광역시,국민임대,29.34,38,0.0,H,-,-,0.0,8.0,664.0,744.0
2908,C2186,924,아파트,대구광역시,국민임대,37.43,220,0.0,H,-,-,0.0,8.0,664.0,744.0